[workspace]
members = ["behavioral/state", "behavioral/strategy", "creational/builder", "creational/prototype", "creational/singleton", "structural/adapter", "structural/facade", "structural/proxy"]

resolver = "3"
